# Generated by Django 3.2.9 on 2022-07-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='bat_imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_1', models.CharField(max_length=250)),
                ('option_2', models.CharField(max_length=250)),
                ('option_3', models.CharField(max_length=250)),
                ('option_4', models.CharField(max_length=250)),
                ('level', models.CharField(max_length=120)),
                ('time_limit', models.IntegerField()),
                ('right_option', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quizcategory')),
            ],
        ),
    ]
